/*
 * Copyright (c) 2022 LasGIS FOE Helper
 */

export const SKILLS_EDIT_SKILL_SHOW = 'SKILLS_EDIT_SKILL_SHOW';
export const SKILLS_SET_IS_NEW_SKILL = 'SKILLS_SET_IS_NEW_SKILL';
export const SKILLS_SEARCH_VALUE = 'SKILLS_SEARCH_VALUE';

export const SKILLS_EDIT_NEW_SKILL = 'SKILLS_EDIT_NEW_SKILL';
export const SKILLS_EDIT_SKILL_BY_IP = 'SKILLS_EDIT_SKILL_BY_IP';
export const SKILLS_INSERT_SKILL = 'SKILLS_INSERT_SKILL';
export const SKILLS_UPDATE_SKILL = 'SKILLS_UPDATE_SKILL';
export const SKILLS_DELETE_SKILL = 'SKILLS_DELETE_SKILL';
