/*
 * Copyright 2020 LasGIS FOE Helper
 */

export const RESIDENTIAL_BUILDING_EDIT_SHOW = 'GREAT_BUILDING_EDIT_SHOW';
export const RESIDENTIAL_BUILDING_SET_IS_NEW = 'GREAT_BUILDING_SET_IS_NEW';

export const RESIDENTIAL_BUILDING_EDIT_NEW = 'GREAT_BUILDING_EDIT_NEW';
export const RESIDENTIAL_BUILDING_EDIT_BY_IP = 'GREAT_BUILDING_EDIT_BY_IP';
export const RESIDENTIAL_BUILDING_INSERT = 'GREAT_BUILDING_INSERT';
export const RESIDENTIAL_BUILDING_UPDATE = 'GREAT_BUILDING_UPDATE';
export const RESIDENTIAL_BUILDING_DELETE = 'GREAT_BUILDING_DELETE';
